# -*- coding: utf-8 -*-
"""15 March 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NAI55G31nrAe5OV0oyPByPHZcE4iwXJ

# Convert RGB image to grayscale
"""

from google.colab import files
uploaded = files.upload()

# Import libraries
import cv2
import matplotlib.pyplot as plt
img = cv2.imread("watch.jpg")

plt.imshow(img, cmap='gray')
plt.axis("off")
plt.show()
# Read image
img = cv2.imread("watch.jpg", cv2.IMREAD_GRAYSCALE)

# Show image
plt.imshow(img, cmap='gray')
plt.axis("off")
plt.show()

## create one window and resize and then add image to that window
#cv2.namedWindow("Image Output",cv2.WINDOW_NORMAL)
#cv2.imshow("Image Output",img)

# set wait key so when i type, output window disappear
#cv2.waitKey(0)

"""# Reading and saving the image"""

import cv2
from google.colab.patches import cv2_imshow
# read image from folder and show it
image=cv2.imread("watch.jpg")
cv2_imshow(image)

# read image and convert into grayscale and save image with different format
grayscale=cv2.imread("watch.jpg",cv2.IMREAD_GRAYSCALE)
cv2_imshow(grayscale)
cv2.imwrite("output.png",grayscale)

"""# Compressing image"""

import cv2

image=cv2.imread("watch.jpg")
# 0  → worst quality
# 100 → best quality
cv2.imwrite("output.jpeg",image,[cv2.IMWRITE_JPEG_QUALITY,10])

"""# Converting image RGB to YUV color model"""

import cv2
from google.colab.patches import cv2_imshow
# read image and display
image=cv2.imread("watch.jpg")
cv2_imshow(image)

# convert RGB image to YUV color model and display image
yuv_iamge=cv2.cvtColor(image,cv2.COLOR_BGR2YUV)
cv2_imshow(yuv_iamge)

# display each channel in YUV
y,u,v=cv2.split(yuv_iamge)

cv2_imshow(y)
cv2_imshow(u)
cv2_imshow(v)

"""# Image translation

"""

# Notes:
# translation is like sliding a photo on a table

import numpy as np

img=cv2.imread("watch.jpg")
num_row,num_col=img.shape[:2]
# use identity matrix so that image scale and orientation is same just move the image right and down

translation=np.float32([[1,0,70],[0,1,110]])
# add so that image will fit output screen
img_translation=cv2.warpAffine(img,translation,(num_col+70,num_row+110))
# if i want to move left and up and just give negative value
translation=np.float32([[1,0,-80],[0,1,-90]])
img_translation=cv2.warpAffine(img_translation,translation,(num_col+70+80,num_row+110+90))
cv2_imshow(img_translation)

"""# Image translation and rotation"""

import cv2
import numpy as np


img=cv2.imread("watch.jpg")
num_row,num_col=img.shape[:2]
# move image right and down by half of image width and height
translation_matrix=np.float32([[1,0,num_col*0.5],[0,1,num_row*0.5]])
# creating rotation instruction, num_col num_row tells what should be orgin of roation
# we can also give num_col /2 and num_row_2 give angle of ratoation and sclaing
rotation_matrix=cv2.getRotationMatrix2D((num_col,num_row),30,1)

# apply image translation
img_translation=cv2.warpAffine(img,translation_matrix,(2*num_col,2*num_row))
# apply image rotation
img_rotation=cv2.warpAffine(img_translation,rotation_matrix,(2*num_col,2*num_row))


cv2_imshow(img_rotation)

